name: Build Indexer in India and Ireland (Push Tag)

on:
  push:
    tags:
      - '*.*.*-india'
      - '*.*.*-ire'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_repo: ${{ steps.set-vars.outputs.image_repo }}
      repository_name: ${{ steps.setup.outputs.repository_name }}
    steps:
      - name: Setup outputs
        id: setup
        run: |
          export GITHUB_REPOSITORY_NAME="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
          {
            echo "repository_name=${GITHUB_REPOSITORY_NAME}"
          } | tee -a "${GITHUB_OUTPUT}"

          {
            echo "### Workflow Outputs"
            echo "| Variable        | Description     |"
            echo "| --------------- | --------------- |"
            echo "| repository_name | Repository name |"
          } | tee -a "${GITHUB_STEP_SUMMARY}"

      - name: Set Image Repository based on Tag
        id: set-vars
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          if [[ "$TAG" == *"-india"* ]]; then
            echo "image_repo=indexer" >> $GITHUB_OUTPUT
          elif [[ "$TAG" == *"-ire"* ]]; then
            echo "image_repo=rp-indexer-rapidpro" >> $GITHUB_OUTPUT
          fi

  call-workflow:
    uses: weni-ai/actions-workflows/.github/workflows/reusable-workflow.yaml@main
    needs:
      - setup
    with:
      image_repository: ${{ needs.setup.outputs.image_repo }}
      dockerfile: "docker/Dockerfile"
      target_repository: weni-ai/kubernetes-manifests-platform
      target_application: weni-flows/indexer
      target_patch_file: deployment.json
    secrets: inherit      
